export const csvHeaders = [
    "Azonosító",
    "Típus",
    "Cikkszám",
    "Név",
    "Közzétéve",
    "Kiemelt?",
    "Látható a katalógusban",
    "Rövid leírás",
    "Leírás",
    "Akciós ár kezdődátuma",
    "Akciós ár végdátuma",
    "Adó státusz",
    "Adózási osztály",
    "Raktáron?",
    "Készlet",
    "Alacsony készlet mennyiség",
    "Függő rendelés engedélyezése?",
    "Egyedileg értékesítető?",
    "Tömeg (kg)",
    "Hosszúság (mm)",
    "Szélesség (mm)",
    "Magasság (mm)",
    "Engedélyezzük az értékelést?",
    "Vásárlási megjegyzés",
    "Akciós ár",
    "Normál ár",
    "Kategória",
    "Címkék",
    "Szállítási osztály",
    "Képek",
    "Letöltési korlát",
    "Letöltés lejárati napok",
    "Szülő",
    "Csoportosított termékek",
    "Upsell",
    "Keresztértékesítés",
    "Külső URL",
    "Gomb szövege",
    "Pozíció",
    "Meta: _measurement_1",
    "Meta: _measurement_2",
    "Meta: _measurement_3",
    "Meta: _inner_diameter",
    "Meta: _outer_diameter",
    "Meta: _width_2",
    "Meta: _netweight",
    "Meta: _grossweight",
    "Meta: _brand",
    "Meta: _suppliername",
    "Meta: _gws_efp_meta_text",
    "Tulajdonság neve 1",
    "Tulajdonság (1) értéke(i)",
    "Tulajdonság 1 láthatósága",
    "Tulajdonság (1) globális"
]